# Generated by Django 6.1 on 2026-09-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=100)),
                ('detected_urls', models.TextField(blank=True)),
                ('matched_keywords', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
